services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - MONGO_URI=${MONGO_URI}  # Use MONGO_URI from .env
    volumes:
      - .:/app
    working_dir: /app


volumes:
  mongo-data: